### PR TITLE
Use new signature for `text!`

### PR DESCRIPTION
**Pull request by greimel**

### CODE REVIEW

**Comment by hexaeder** [comment]
Will this be the interface in Makie`v0.20`? Had a quick look at the repo but didn't find it there

**Comment by greimel** [comment]
I am confused as well. That was changed a while ago and that's how it is documented https://docs.makie.org/v0.19/examples/plotting_functions/text/index.html#text

I am surprised that the old signature still works. And I am surprised that this change breaks CI.

**Comment by greimel** [comment]
This was apparently changed in around Makie 17.6 (that's when I made a similiar PR to AoG https://github.com/MakieOrg/AlgebraOfGraphics.jl/pull/410)

@jkrumbiegel what's the recommended way forward? will the old (now undocumented) API `text(labels; position)` stay around?

**Comment by jkrumbiegel** [comment]
Recommended is to use `text` like `scatter` etc, where the positional args go through the conversion pipeline and refer to locations in the plot, not decorations like the particular strings that appear there. I only left in the old version at the time to reduce breakage. Might be removed at some point.

**Comment by hexaeder** [comment]
Thanks for the clarification! So i guess this PR is right and we just need to fix the accessor functions for the node/edgelable plots. It seems like this is the only broken thing

**Comment by greimel** [comment]
Tests pass now! @hexaeder, it would be nice if you could tag this soon. After this PR one can use it with a patched version of MakieTeX.jl

**Comment by hexaeder** [comment]
Sure! I started the tagging process. Thanks for the fix!

**Pull request merged**
