### PR TITLE
`arrow_shift = :end` moves arrowhead tip to surface of destination node marker.

### LINKED ISSUE #101: Feature request: `arrow_shift = 1` land arrow on the surface of the node marker
It would be great to be able to set the arrow shift parameter to 1 and have the tip of the arrow land on the edge (surface) of the node, not on the center of the node. This would be the preferred behavior. This will require taking into account the size of the marker.

The current work around is to pass a vector of arrow shifts to try to get them to land on the surface of each node (requires some trial and error).

### PR DESCRIPTION
**Pull request by hdavid16**
Replaces #108 

Closes #101, #107, #109, #112

### CODE REVIEW

**Comment by hexaeder** [comment]
Hey, one last question:
```julia
using GraphMakie: SquareGrid
g = SimpleDiGraph(8)
add_edge!(g, 1, 2)
add_edge!(g, 3, 4)
add_edge!(g, 5, 6)
add_edge!(g, 7, 8)

fig, ax, p = graphplot(g; arrow_shift=:end, layout=SquareGrid(cols=2),
                       node_size=[10, 10, 10,200,10,350,10,500])
xlims!(-.5,1.5)
ylims!(-3.5,.5)
```
grafik

it seems like the distance between arrow and marker grows bigger with large markers. Any idea whats happening there? Is this just due to some small inaccuracy in the marker basesize or is it a hint at a bug in the algorithm?

**Comment by hdavid16** [comment]
@hexaeder good corner case to test. It does have to do with the base size. If I use `Circle` and `Arrow` for the node and arrowhead markers, which have a `1x1` base size, the plot is correct (I added transparency so you can see the arrowhead):

image

I'm going to look into how the makie markers are scaling with size...

**Comment by hdavid16** [comment]
The last commit, will fix this corner case. It uses the default `:circle` marker:
image

**Review by hexaeder — APPROVED** [review]

**Comment by hexaeder** [comment]
thanks a lot for implementing this nice feature! :)

**Pull request merged**
