### PR TITLE
allow vector of points for layout

### PR DESCRIPTION
**Pull request by maltesie**
This adds the possibility to pass a vector of things that can be converted to Pointf to the layout kwarg.

### CODE REVIEW

**Comment by greimel** [comment]
FYI: The failing reftest also fails on master. So it's not your fault ;-)

**Comment by maltesie** [comment]
@hexaeder showed me the failing test and if I remember correctly it is caused by reftests.jl-12.png. Something in Makie changed and the line segments are rendered differently in this graph. There should be an updated version of the file named retests.jl-12+.png, but I cannot find it anywhere. If anyone can point me to it, I would try and make a PR updating the file. Otherwise I could try to create an updated one myself...

**Comment by hexaeder** [comment]
You need to run the tests locally, `] test` on master branch. That will create updated version of the reference images in the `assets/` folder. After running the test, there should be two files:

- `assets/reftests-12.png`
- `assets/reftests-12+.png`

where the `+` denotes the updated file. If you delete the one without plus, delete the plus on the other one and create a PR the tests should run through

**Review by greimel — CHANGES_REQUESTED** [review]
Looks great! I have two minor suggestions to make the code a little cleaner.

For testing the feature, you could look through the code base and replace `_ -> points` by `points`.

E.g. here
https://github.com/MakieOrg/GraphMakie.jl/blob/813aa93b95f4a4cbc82ea19217715bd5e7638f3d/docs/examples/reftests.jl#L97

https://github.com/MakieOrg/GraphMakie.jl/blob/813aa93b95f4a4cbc82ea19217715bd5e7638f3d/docs/examples/reftests.jl#L133

https://github.com/MakieOrg/GraphMakie.jl/blob/813aa93b95f4a4cbc82ea19217715bd5e7638f3d/docs/examples/plots.jl#L277

Please also adjust this line

https://github.com/MakieOrg/GraphMakie.jl/blob/813aa93b95f4a4cbc82ea19217715bd5e7638f3d/src/recipes.jl#L29

to reflect your new feature.

**Review by greimel — APPROVED** [review]

**Comment by maltesie** [comment]
Thanks for the review :) was that correct to request a new review after I'm done with the chenges?

**Comment by greimel** [comment]
Yes, that's perfect! Thanks for your effort. Let's see if @hexaeder has anything to add. But I assume this will be merged soon.

**Pull request merged**
